### ISSUE TITLE
Error if you try to add more than 6 stock accounts

### ISSUE THREAD

**Issue by kennydrobnack** [jokorn/buckets_dashboard#2]
I'm trying to use the new Stock functionality in the Buckets Dashboard and found out there seems to be a limit to the number of stock accounts you can add.

I am using the latest version of buckets_dashboard and the latest stable version of Buckets 0.72.2 on a Mac running MacOS 14.5

I did some experimenting and it seems to hit problems once I select 7. I also tried adding extra accounts for testing and if I have 8 accounts selected as stock accounts, it does indeed say size 8 in the error instead of 7. Here is the error:

  97: renderUI [buckets_dashboard/server.R#403]
   96: func
   83: renderFunc
   82: output$stock_transfers
    1: runApp
Warning: Error in filter: ℹ In argument: `account == input$stock_account`.
Caused by error:
! `..1` must be of size 6 or 1, not size 7.
  121: <Anonymous>
  120: signalCondition
  119: signal_abort
  118: abort
  117: <Anonymous>
  116: signalCondition
  115: signal_abort
  114: abort
  113: dplyr_internal_error
  112: eval
  111: mask$eval_all_filter
  109: filter_eval
  108: filter_rows
  107: filter.data.frame
  106: filter
  105: distinct
  104: arrange
  103: pull
  102: %>%
   97: renderUI [buckets_dashboard/server.R#420]
   96: func
   83: renderFunc
   82: output$stock_gains
    1: runApp
Warning: Can only have one: config
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.

**Comment by jokorn** [comment]
Thank you for reporting this issue. I have tried fixing it now in commit [76ab352](https://github.com/jokorn/buckets_dashboard/commit/76ab352481843f9f7cb788d88ea457e827ce3820). Can you test the newest version?

**Comment by kennydrobnack** [comment]
I finally had a chance to test it. I selected all my off-budget accounts just for fun and it worked with no issues. Thanks for the quick fix!

**Comment by jokorn** [comment]
Fixed by [76ab352](https://github.com/jokorn/buckets_dashboard/commit/76ab352481843f9f7cb788d88ea457e827ce3820)
